-- Migration: switch exercise videos to Cloudinary
-- Run in Supabase SQL editor.

alter table exercises add column if not exists cloudinary_id text;

update exercises set cloudinary_id='Strong_Partner_jjyiue' where name='Strong Partner';
update exercises set cloudinary_id='Turnout_Developer_Plank_kpjhl3' where name='Turnout Developer Plank';
update exercises set cloudinary_id='Single_Leg_Deadlift_ek9hy9' where name='Single Leg Deadlift';
update exercises set cloudinary_id='Turnout_Developer_mnankw' where name='Turnout Developer';
update exercises set cloudinary_id='Tricep_Chest_Dip_izn4fx' where name='Tricep Chest Dip';
update exercises set cloudinary_id='Squat_Jump_boyere' where name='Squat Jump';
update exercises set cloudinary_id='Squat_tsco6d' where name='Squat';
update exercises set cloudinary_id='Paralell_Front_Split_Slides_huqrki' where name='Paralell Front Split Slides';
update exercises set cloudinary_id='Step_Elevated_Hip_Extension_Lunge_c528u8' where name='Step Elevated Hip Extension Lunge';
update exercises set cloudinary_id='Single_Leg_Hip_Flexor_Raise_j1sxec' where name='Single Leg Hip Flexor Raise';
update exercises set cloudinary_id='Slant_Board_Squat_ncthzs' where name='Slant Board Squat';
update exercises set cloudinary_id='Side_Hop_To_Reverse_Lunge_wkzc9u' where name='Side Hop To Reverse Lunge';
update exercises set cloudinary_id='Side_Lunge_To_A_La_Second_zefu7a' where name='Side Lunge To A La Second';
update exercises set cloudinary_id='Seated_Barbell_Overhead_Press_tump4t' where name='Seated Barbell Overhead Press';
update exercises set cloudinary_id='Side_Split_Walkouts_htgtcc' where name='Side Split Walkouts';
update exercises set cloudinary_id='Reverse_Lunge_To_Rond_De_Jambe_t4cflc' where name='Reverse Lunge To Rond De Jambe';
update exercises set cloudinary_id='Roll_Through_Pushups_k3iok0' where name='Roll Through Pushups';
update exercises set cloudinary_id='Nordic_Hamstring_Curls_gsuqa7' where name='Nordic Hamstring Curls';
update exercises set cloudinary_id='Pushup_On_Knees_ujvsux' where name='Pushup On Knees';
update exercises set cloudinary_id='Pushup_On_Toes_eowrce' where name='Pushup On Toes';
update exercises set cloudinary_id='Pushup_On_Knees_With_Mountain_Climber_om5l7j' where name='Pushup On Knees With Mountain Climber';
update exercises set cloudinary_id='Palloff_Press_w4dsto' where name='Palloff Press';
update exercises set cloudinary_id='Lat_Pulls_xhertw' where name='Lat Pulls';
update exercises set cloudinary_id='Lat_Press_Downs_xcosfn' where name='Lat Press Downs';
update exercises set cloudinary_id='Overhead_Press_In_Second_obq3sm' where name='Overhead Press In Second';
update exercises set cloudinary_id='Hip_Extension_Lunge_s0pnze' where name='Hip Extension Lunge';
update exercises set cloudinary_id='L-Sit_Battu_nyotoh' where name='L-Sit Battu';
update exercises set cloudinary_id='Kneeling_Quadricep_Extensions_ml1lsl' where name='Kneeling Quadricep Extensions';
update exercises set cloudinary_id='Hanstand_bmykyp' where name='Hanstand';
update exercises set cloudinary_id='Extension_Developer_Side_lhzg5h' where name='Extension Developer Side';
update exercises set cloudinary_id='Barbell_Clean_dpeil1' where name='Barbell Clean';
update exercises set cloudinary_id='Barbell_Overhead_Strict_Press_kz7rht' where name='Barbell Overhead Strict Press';
update exercises set cloudinary_id='Hanging_Knee_Raise_cz2ynd' where name='Hanging Knee Raise';
update exercises set cloudinary_id='Dumbbell_Bench_Row_wddjet' where name='Dumbbell Bench Row';
update exercises set cloudinary_id='Extension_Developer_Back_n0cejo' where name='Extension Developer Back';
update exercises set cloudinary_id='Extension_Developer_Front_whwdnd' where name='Extension Developer Front';
update exercises set cloudinary_id='Deadlift_xgudda' where name='Deadlift';
update exercises set cloudinary_id='Deficit_Pushup_a2yuha' where name='Deficit Pushup';
update exercises set cloudinary_id='Deep_Knee_Bend_lz5n0e' where name='Deep Knee Bend';
update exercises set cloudinary_id='Cross_Body_Extensions_rzy7id' where name='Cross Body Extensions';
update exercises set cloudinary_id='Barbell_Snatch_aebwsl' where name='Barbell Snatch';
update exercises set cloudinary_id='Barbell_Hip_Extension_Lunge_dpizwa' where name='Barbell Hip Extension Lunge';
update exercises set cloudinary_id='Barbell_Bench_Press_ltfqja' where name='Barbell Bench Press';
update exercises set cloudinary_id='Chair_Elevated_Hip_Extension_Lunge_yqeppu' where name='Chair Elevated Hip Extension Lunge';
update exercises set cloudinary_id='Cross_Body_Extensions_2_uia7u2' where name='Cross Body Extensions 2';
update exercises set cloudinary_id='Barbell_Back_Squat_dn9nc1' where name='Barbell Back Squat';
update exercises set cloudinary_id='Band_Row_ibf0ce' where name='Band Row';
update exercises set cloudinary_id='Assisted_Negative_Dips_zpfvvu' where name='Assisted Negative Dips';
update exercises set cloudinary_id='Bent_Over_Row_jiljmh' where name='Bent Over Row';
update exercises set cloudinary_id='Band_Deadlift_i9ozid' where name='Band Deadlift';
update exercises set cloudinary_id='Battu_Strength_tmimr9' where name='Battu Strength';
update exercises set cloudinary_id='Arabesque_Port_De_Bras_klohgx' where name='Arabesque Port De Bras';
update exercises set cloudinary_id='Angled_Calf_Raise_m3yf8a' where name='Angled Calf Raise';
update exercises set cloudinary_id='Arabesque_Row_b0nvrf' where name='Arabesque Row';
update exercises set cloudinary_id='Anterior_Tibialis_Raises_c2agpt' where name='Anterior Tibialis Raises';
update exercises set cloudinary_id='Arabesque_Kicks_kv1lnm' where name='Arabesque Kicks';
update exercises set cloudinary_id='Bent_Knee_Calf_Raise_tzqifi' where name='Bent Knee Calf Raise';
update exercises set cloudinary_id='Adductor_Isometric_Squat_Hold_egaqsw' where name='Adductor Isometric Squat Hold';
