"use client";

// Adapted from "Mesh Gradient" by @paper-design on 21st.dev, generated by the
// 21st.dev Shader Builder. Original adapted from Paper Shaders, Apache-2.0:
// https://shaders.paper.design/mesh-gradient
//
// Changes from the original:
//  - Palette swapped from the Beach variant (pink/violet/yellow) to the
//    Athletistry stone-and-royal-blue set, so it reads as light moving through
//    polished stone rather than a synthwave poster.
//  - prefers-reduced-motion renders a static CSS gradient and never creates a
//    WebGL context or a rAF loop at all.
//  - Dead GLSL removed: this variant runs with oklab, blur and cursor all off,
//    which left the OKLab conversion pair, mixColour, palette and the entire
//    cursor distortion block unreachable. Same output, far less to read.
//  - Pointer tracking and its five window listeners removed with them.
//
// Retained from the original, because they are the parts that make a shader
// affordable on a phone: IntersectionObserver pauses the loop off-screen,
// visibilitychange pauses it on tab hide, DPR is capped at 2 and total pixels
// at 2M, and the context is released on unmount.

import { useEffect, useRef, useState } from "react";

const VERT = `attribute vec2 a_position;
void main() {
  gl_Position = vec4(a_position, 0.0, 1.0);
}`;

const FRAG = `#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec3 u_colors[8];
uniform vec4 u_scene;      // resolution.xy, time, colour count
uniform vec4 u_shape;      // scale, intensity, paramA, warp
uniform vec4 u_surface;    // detail, contrast, brightness, saturation
uniform vec4 u_finish;     // hue, vignette, unused, grain
uniform vec4 u_transform;  // seed, rotation, drift, unused

#define u_resolution u_scene.xy
#define u_time u_scene.z
#define u_colorCount u_scene.w
#define u_scale u_shape.x
#define u_intensity u_shape.y
#define u_paramA u_shape.z
#define u_warp u_shape.w
#define u_detail u_surface.x
#define u_contrast u_surface.y
#define u_brightness u_surface.z
#define u_saturation u_surface.w
#define u_hue u_finish.x
#define u_vignette u_finish.y
#define u_grain u_finish.w
#ifdef GL_FRAGMENT_PRECISION_HIGH
#define u_seed u_transform.x
#else
#define u_seed mod(u_transform.x, 31.0)
#endif
#define u_rotate u_transform.y
#define u_drift u_transform.z

float hash21(vec2 p) {
#ifndef GL_FRAGMENT_PRECISION_HIGH
  p = mod(p, 31.0);
#endif
  p = fract(p * vec2(234.34, 435.345));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

// Dave Hoskins hash12: even white noise for the grain. The multiply hash above
// shows a faint axis-aligned mesh at integer coords, which reads as a net.
float grainHash(vec2 p) {
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

float noise(vec2 p) {
  vec2 i = floor(p);
  vec2 f = fract(p);
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(
    mix(hash21(i), hash21(i + vec2(1.0, 0.0)), u.x),
    mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0, 1.0)), u.x),
    u.y);
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p = p * 2.03 + vec2(17.0, 9.2);
    a *= 0.5;
  }
  return v;
}

vec3 hueRotate(vec3 col, float a) {
  const mat3 toYIQ = mat3(0.299, 0.596, 0.211,
                          0.587, -0.274, -0.523,
                          0.114, -0.322, 0.312);
  const mat3 toRGB = mat3(1.0, 1.0, 1.0,
                          0.956, -0.272, -1.106,
                          0.621, -0.647, 1.703);
  vec3 yiq = toYIQ * col;
  float ca = cos(a), sa = sin(a);
  yiq = vec3(yiq.x, yiq.y * ca - yiq.z * sa, yiq.y * sa + yiq.z * ca);
  return toRGB * yiq;
}

vec3 shade(vec2 p, float t) {
  vec3 color = u_colors[0] * 0.16;
  float weight = 0.16;
  for (int i = 0; i < 8; i++) {
    if (float(i) >= u_colorCount) break;
    float fi = float(i);
    vec2 center = vec2(sin(fi * 2.17 + t * 0.13 + u_seed),
                       cos(fi * 1.63 - t * 0.11)) * (0.22 + u_intensity * 0.62);
    float falloff = mix(12.0, 2.4, u_paramA);
    float influence = exp(-dot(p - center, p - center) * falloff);
    color += u_colors[i] * influence;
    weight += influence;
  }
  return color / weight;
}

void main() {
  vec2 screenUv = gl_FragCoord.xy / u_resolution.xy;
  vec2 p = (gl_FragCoord.xy - 0.5 * u_resolution.xy)
    / min(u_resolution.x, u_resolution.y);

  p *= u_scale;
  if (abs(u_rotate) > 0.0001) {
    float cr = cos(u_rotate), sr = sin(u_rotate);
    p = mat2(cr, -sr, sr, cr) * p;
  }
  if (u_drift > 0.0001)
    p += u_drift * vec2(sin(u_time * 0.31), cos(u_time * 0.23));
  if (u_warp > 0.0) {
    p += u_warp * (vec2(
      fbm(p * u_detail + u_seed),
      fbm(p * u_detail + vec2(5.2, 1.3))) - 0.5);
  }

  vec3 col = shade(p, u_time);

  if (abs(u_contrast - 1.0) > 0.0001)
    col = (col - 0.5) * u_contrast + 0.5;
  if (abs(u_saturation - 1.0) > 0.0001) {
    float luma = dot(col, vec3(0.299, 0.587, 0.114));
    col = mix(vec3(luma), col, u_saturation);
  }
  if (abs(u_hue) > 0.0001)
    col = hueRotate(col, u_hue);
  if (abs(u_brightness) > 0.0001)
    col += u_brightness;
  if (u_vignette > 0.0001) {
    float vd = length(screenUv - 0.5) * 1.41421356;
    col *= 1.0 - u_vignette * smoothstep(0.35, 1.0, vd);
  }
  if (u_grain > 0.0001)
    col += (grainHash(
      gl_FragCoord.xy + vec2(u_seed * 17.0, u_seed * 31.0)) - 0.5) * u_grain;
  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}
`;

// Athletistry palette: graphite #15181d, deep navy #102b56, royal #255fbd,
// and #6798e2 as the light catching the top edge.
const UNIFORMS = {
  colors: [
    [0.0824, 0.0941, 0.1137],
    [0.0627, 0.1686, 0.3373],
    [0.1451, 0.3725, 0.7412],
    [0.4039, 0.5961, 0.8863],
    [0.4039, 0.5961, 0.8863],
    [0.4039, 0.5961, 0.8863],
    [0.4039, 0.5961, 0.8863],
    [0.4039, 0.5961, 0.8863],
  ] as [number, number, number][],
  colorCount: 4,
  scale: 1.74,
  intensity: 0.78,
  paramA: 0.34,
  warp: 0.09,
  detail: 2.4,
  contrast: 1.04,
  brightness: -0.02,
  saturation: 0.94,
  hue: 0,
  vignette: 0.22,
  grain: 0.085,
  seed: 3,
  rotate: 1.9373,
  drift: 0.03,
  timeScale: 0.52,
};

const STATIC_FALLBACK =
  "radial-gradient(circle at 78% 22%, #255fbd 0%, transparent 42%)," +
  "radial-gradient(circle at 22% 78%, #102b56 0%, transparent 46%)," +
  "linear-gradient(122deg, #15181d 0%, #1b2027 30%, #15181d 62%, #102b56 130%)";

export function ShaderHero({ className }: { className?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [reduced, setReduced] = useState<boolean | null>(null);
  // The upstream component never checks compile or link status, so a GLSL
  // error renders as a silent black rectangle. Fall back to the gradient.
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    setReduced(mq.matches);
    const on = () => setReduced(mq.matches);
    mq.addEventListener("change", on);
    return () => mq.removeEventListener("change", on);
  }, []);

  useEffect(() => {
    if (reduced !== false || failed) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const maybeGl = canvas.getContext("webgl", { antialias: false });
    if (!maybeGl) {
      setFailed(true);
      return;
    }
    // Bind the narrowed context to its own const. `render` is a hoisted
    // function declaration, and TypeScript won't carry a null-narrowing into
    // one, since in principle it could be called before the check runs.
    const gl: WebGLRenderingContext = maybeGl;

    const compile = (type: number, src: string) => {
      const sh = gl.createShader(type)!;
      gl.shaderSource(sh, src);
      gl.compileShader(sh);
      if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {
        console.error("[ShaderHero] shader compile failed:", gl.getShaderInfoLog(sh));
        gl.deleteShader(sh);
        return null;
      }
      return sh;
    };
    const vs = compile(gl.VERTEX_SHADER, VERT);
    const fs = compile(gl.FRAGMENT_SHADER, FRAG);
    if (!vs || !fs) {
      setFailed(true);
      return;
    }
    const program = gl.createProgram()!;
    gl.attachShader(program, vs);
    gl.attachShader(program, fs);
    gl.linkProgram(program);
    gl.deleteShader(vs);
    gl.deleteShader(fs);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      console.error("[ShaderHero] program link failed:", gl.getProgramInfoLog(program));
      gl.deleteProgram(program);
      setFailed(true);
      return;
    }
    gl.useProgram(program);

    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);
    const loc = gl.getAttribLocation(program, "a_position");
    gl.enableVertexAttribArray(loc);
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);

    const uni = {
      colors: gl.getUniformLocation(program, "u_colors"),
      scene: gl.getUniformLocation(program, "u_scene"),
      shape: gl.getUniformLocation(program, "u_shape"),
      surface: gl.getUniformLocation(program, "u_surface"),
      finish: gl.getUniformLocation(program, "u_finish"),
      transform: gl.getUniformLocation(program, "u_transform"),
    };
    gl.uniform3fv(uni.colors, new Float32Array(UNIFORMS.colors.flat()));
    gl.uniform4f(uni.shape, UNIFORMS.scale, UNIFORMS.intensity, UNIFORMS.paramA, UNIFORMS.warp);
    gl.uniform4f(uni.surface, UNIFORMS.detail, UNIFORMS.contrast, UNIFORMS.brightness, UNIFORMS.saturation);
    gl.uniform4f(uni.finish, UNIFORMS.hue, UNIFORMS.vignette, 0, UNIFORMS.grain);
    gl.uniform4f(uni.transform, UNIFORMS.seed, UNIFORMS.rotate, UNIFORMS.drift, 0);

    let bounds = canvas.getBoundingClientRect();
    let raf = 0;
    let visible = document.visibilityState === "visible";
    let inView = true;
    let disposed = false;
    const start = performance.now();

    const resizeCanvas = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      const rawW = Math.max(1, Math.round(bounds.width * dpr));
      const rawH = Math.max(1, Math.round(bounds.height * dpr));
      const pixelScale = Math.min(1, Math.sqrt(2_000_000 / Math.max(1, rawW * rawH)));
      const width = Math.max(1, Math.round(rawW * pixelScale));
      const height = Math.max(1, Math.round(rawH * pixelScale));
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width;
        canvas.height = height;
        gl.viewport(0, 0, width, height);
      }
    };

    function requestRender() {
      if (!disposed && visible && inView && raf === 0) raf = requestAnimationFrame(render);
    }

    const updateLayout = () => {
      bounds = canvas.getBoundingClientRect();
      resizeCanvas();
      requestRender();
    };
    window.addEventListener("resize", updateLayout);

    const ro = new ResizeObserver(updateLayout);
    ro.observe(canvas);
    const io = new IntersectionObserver(([entry]) => {
      inView = entry?.isIntersecting ?? true;
      if (inView) requestRender();
      else if (raf !== 0) {
        cancelAnimationFrame(raf);
        raf = 0;
      }
    });
    io.observe(canvas);
    const onVisibility = () => {
      visible = document.visibilityState === "visible";
      if (visible) requestRender();
      else if (raf !== 0) {
        cancelAnimationFrame(raf);
        raf = 0;
      }
    };
    document.addEventListener("visibilitychange", onVisibility);

    function render(now: number) {
      raf = 0;
      if (disposed || !visible || !inView) return;
      resizeCanvas();
      gl.uniform4f(
        uni.scene,
        canvas.width,
        canvas.height,
        ((now - start) / 1000) * UNIFORMS.timeScale,
        UNIFORMS.colorCount,
      );
      gl.drawArrays(gl.TRIANGLES, 0, 3);
      requestRender();
    }
    requestRender();

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      ro.disconnect();
      io.disconnect();
      document.removeEventListener("visibilitychange", onVisibility);
      window.removeEventListener("resize", updateLayout);
      gl.deleteBuffer(buf);
      gl.deleteProgram(program);
      gl.getExtension("WEBGL_lose_context")?.loseContext();
    };
  }, [reduced, failed]);

  // Until the media query has been read, and whenever motion is reduced, paint
  // the static gradient. No context, no loop.
  if (reduced !== false || failed) {
    return <div className={className} style={{ background: STATIC_FALLBACK }} aria-hidden />;
  }

  return (
    <canvas
      ref={canvasRef}
      className={className}
      aria-hidden
      style={{ display: "block", width: "100%", height: "100%" }}
    />
  );
}

export default ShaderHero;
